[package]
name = "mapal-backend-llvm"
version.workspace = true
edition.workspace = true

[dependencies]
mapal-ir = { path = "../../mapal-ir" }
slotmap = "1.0"

[dev-dependencies]
mapal-syntax = { path = "../../mapal-syntax" }
mapal-lower = { path = "../../mapal-lower" }
mapal-interp = { path = "../../mapal-interp" }
mapal-rewrite = { path = "../../mapal-rewrite" }
insta = "1.47.2"
tempfile = "3.27.0"
proptest = "1.11.0"
