[package]
name = "mapal-lower"
version.workspace = true
edition.workspace = true

[dependencies]
mapal-syntax = { path = "../mapal-syntax" }
mapal-ir = { path = "../mapal-ir" }

[dev-dependencies]
insta = "1.47.2"
proptest = "1.11.0"
criterion = "0.5.1"

[[bench]]
name = "lower_scale"
harness = false
