[package]
name = "flow-backend-cuda"
version.workspace = true
edition.workspace = true

[dependencies]
flow-ir = { path = "../../flow-ir" }
slotmap = "1.0"

[dev-dependencies]
flow-syntax = { path = "../../flow-syntax" }
flow-lower = { path = "../../flow-lower" }
flow-interp = { path = "../../flow-interp" }
flow-rewrite = { path = "../../flow-rewrite" }
insta = "1.47.2"
tempfile = "3.27.0"
proptest = "1.11.0"
