[package]
name = "mapal-interp"
version.workspace = true
edition.workspace = true

[dependencies]
mapal-ir = { path = "../mapal-ir" }
slotmap = "1.0"

[dev-dependencies]
mapal-syntax = { path = "../mapal-syntax" }
mapal-lower = { path = "../mapal-lower" }
criterion = "0.5.1"

[[bench]]
name = "interp_scale"
harness = false
